<a href="https://colab.research.google.com/github/Hyon2-park/test/blob/main/%EC%A2%8C%ED%91%9C%EB%B3%80%ED%99%98%EC%B5%9C%EC%A2%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df=pd.read_csv('/content/risk_all.csv')
df1=pd.read_csv('/content/전체좌표변환.csv',encoding='cp949')

In [4]:
df.rename({'lon':'경도','lat':'위도'},inplace=True)
df.drop(columns=['source_file'],inplace=True)
df.drop_duplicates(['lon','lat'],inplace=True)
df.reset_index(drop=True,inplace=True)

In [8]:
df.rename(columns={'lon':'경도','lat':'위도'},inplace=True)

In [14]:
df1=df1.drop(columns=['Unnamed: 0'])
df1

                 경도         위도                         주소
0        126.551082  35.033890   전라남도 함평군 학교면 죽정리 897-3번지
1        126.554708  35.046247     전라남도 함평군 학교면 마산리 224번지
2        126.527044  35.054765  전라남도 함평군 함평읍 기각리 1100-1번지
3        126.527162  35.056294  전라남도 함평군 함평읍 기각리 1099-7번지
4        126.532545  35.041756  전라남도 함평군 학교면 월산리 1412-2번지
...             ...        ...                        ...
1004587  127.399558  35.366191  전북특별자치도 남원시 주천면 주천리 산67번지
1004588  127.394452  35.441594    전북특별자치도 남원시 고죽동 산87-1번지
1004589  127.394215  35.402987   전북특별자치도 남원시 어현동 37-201번지
1004590  127.394337  35.402307    전북특별자치도 남원시 어현동 37-99번지
1004591  127.395026        NaN                        NaN

[1004592 rows x 3 columns]

In [16]:
df1=df1.drop_duplicates()

In [21]:
total=pd.merge(df,df1,on=['경도','위도'],how='right')
total

,ucb,infil_1_5,human_1_5,total_risk,risk_binary,경도,위도,주소
0,4210.0,5.0,1.0,2.40,0.0,126.551082,35.033890,전라남도 함평군 학교면 죽정리 897-3번지
1,3210.0,1.0,3.0,2.30,0.0,126.554708,35.046247,전라남도 함평군 학교면 마산리 224번지
2,2120.0,4.0,1.0,2.05,0.0,126.527044,35.054765,전라남도 함평군 함평읍 기각리 1100-1번지
3,2120.0,4.0,1.0,2.05,0.0,126.527162,35.056294,전라남도 함평군 함평읍 기각리 1099-7번지
4,2230.0,2.0,1.0,1.35,0.0,126.532545,35.041756,전라남도 함평군 학교면 월산리 1412-2번지
...,...,...,...,...,...,...,...,...
434076,1210.0,3.0,2.0,2.35,0.0,127.983218,36.735949,충청북도 괴산군 연풍면 주진리 661-7번지
434077,1210.0,3.0,2.0,2.35,0.0,127.984863,36.773013,충청북도 괴산군 연풍면 행촌리 산49번지
434078,1210.0,3.0,2.0,2.35,0.0,127.984630,36.766782,충청북도 괴산군 연풍면 행촌리 913번지
434079,1210.0,3.0,2.0,2.35,0.0,127.983053,36.730644,충청북도 괴산군 연풍면 주진리 산51번지
434080,NaN,NaN,NaN,NaN,NaN,127.395026,NaN,NaN

In [23]:
total.isnull().sum()

ucb            1
infil_1_5      1
human_1_5      1
total_risk     1
risk_binary    1
경도             0
위도             1
주소             1
dtype: int64

In [25]:
total=total.dropna()

In [26]:
total.isnull().sum()

ucb            0
infil_1_5      0
human_1_5      0
total_risk     0
risk_binary    0
경도             0
위도             0
주소             0
dtype: int64